export { primeNumbers, ALPHABET_CODE, ALPHABET } from './constants.js'
export {
  gcd,
  primeFactorization,
  calcPrimeFactorization,
  numberPrimeFactorization,
  messagePrimeFactorization,
  messageExponential,
  encodeChar,
  asciiToHex,
  hexToBin,
  encodeStringArrayNumber,
  numberToZ26,
} from './mathHandle.js'
export {
  matDecompose,
  vecMake,
  vecInit,
  matMake,
  matInit,
  vecShow,
  matShow,
  matProduct,
  matDeterminant,
  multiplyMatrices,
  matrixInZn,
  multiplyMatrixNumber,
  matInverse,
  reduce,
  det,
} from './matrixHandle.js'

// * IMPORT VÔ FILE NÀO CẦN UTILS RỒI XÓA MẤY CÁI KHÔNG CẦN THIẾT
// import {
//   matDecompose,
//   vecMake,
//   vecInit,
//   matMake,
//   matInit,
//   vecShow,
//   matShow,
//   matProduct,
//   matDeterminant,
//   multiplyMatrices,
//   matrixInZn,
//   multiplyMatrixNumber,
//   matInverse,
//   reduce,
//   det,
//   gcd,
//   calcPrimeFactorization,
//   numberPrimeFactorization,
//   messagePrimeFactorization,
//   messageExponential,
//   encodeChar,
//   asciiToHex,
//   hexToBin,
//   primeNumbers,
//   ALPHABET_CODE,
//   encodeStringArrayNumber,
//   numberToZ26,
// } from '../utils/index.js'
